-- AUK Event & Workshop Attendance System
-- db/schema.sql
--
-- Designed to run in the Supabase SQL Editor
-- on an empty Supabase project.
-- Contains schema only — no real data.
-- ============================================================


-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE public.users (
    user_id UUID PRIMARY KEY
        REFERENCES auth.users(id) ON DELETE CASCADE,
    name VARCHAR(150) NOT NULL,
    phone VARCHAR(30),
    university_id VARCHAR(50) UNIQUE
);


CREATE TABLE public.attendee (
    user_id UUID PRIMARY KEY
        REFERENCES public.users(user_id) ON DELETE CASCADE,
    attendee_type VARCHAR(20) NOT NULL,

    CONSTRAINT attendee_type_check
        CHECK (attendee_type IN ('Student', 'StaffFaculty', 'Guest'))
);


CREATE TABLE public.coordinator (
    user_id UUID PRIMARY KEY
        REFERENCES public.users(user_id) ON DELETE CASCADE,
    office VARCHAR(100),
    department VARCHAR(100)
);


CREATE TABLE public.organizer (
    user_id UUID PRIMARY KEY
        REFERENCES public.users(user_id) ON DELETE CASCADE,
    department VARCHAR(100)
);


CREATE TABLE public.venues (
    venue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_name VARCHAR(150) NOT NULL,
    location VARCHAR(150) NOT NULL,
    room_capacity INTEGER NOT NULL,

    CONSTRAINT room_capacity_check
        CHECK (room_capacity > 0)
);


CREATE TABLE public.events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    event_type VARCHAR NOT NULL,
    event_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    capacity INTEGER NOT NULL,

    coordinator_id UUID NOT NULL
        REFERENCES public.coordinator(user_id) ON DELETE RESTRICT,

    venue_id BIGINT NOT NULL
        REFERENCES public.venues(venue_id) ON DELETE RESTRICT,

    CONSTRAINT event_capacity_check
        CHECK (capacity > 0),

    CONSTRAINT event_time_check
        CHECK (end_time > start_time),

    CONSTRAINT event_type_check
        CHECK (event_type IN ('Play', 'Workshop', 'Seminar'))
);


CREATE TABLE public.bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id UUID NOT NULL
        REFERENCES public.attendee(user_id) ON DELETE CASCADE,

    event_id BIGINT NOT NULL
        REFERENCES public.events(event_id) ON DELETE CASCADE,

    booking_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    status VARCHAR(20) NOT NULL DEFAULT 'Confirmed',

    CONSTRAINT booking_status_check
        CHECK (status IN ('Confirmed', 'Waitlisted', 'Cancelled')),

    CONSTRAINT unique_user_event
        UNIQUE (user_id, event_id)
);


CREATE TABLE public.organizer_assignments (
    event_id BIGINT NOT NULL
        REFERENCES public.events(event_id) ON DELETE CASCADE,

    organizer_id UUID NOT NULL
        REFERENCES public.organizer(user_id) ON DELETE CASCADE,

    PRIMARY KEY (event_id, organizer_id)
);


CREATE TABLE public.attendance_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_id BIGINT NOT NULL UNIQUE
        REFERENCES public.bookings(booking_id) ON DELETE CASCADE,

    organizer_id UUID NOT NULL
        REFERENCES public.organizer(user_id) ON DELETE RESTRICT,

    check_in_time TIMESTAMPTZ,
    check_out_time TIMESTAMPTZ,

    attendance_status VARCHAR(20) NOT NULL,

    CONSTRAINT attendance_status_check
        CHECK (attendance_status IN ('Present', 'Absent')),

    CONSTRAINT checkout_after_checkin
        CHECK (
            check_out_time IS NULL
            OR check_in_time IS NULL
            OR check_out_time >= check_in_time
        )
);


-- ============================================================
-- ROLE / AUTHORIZATION HELPERS
-- ============================================================

CREATE OR REPLACE FUNCTION public.is_attendee()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.attendee
        WHERE user_id = auth.uid()
    );
$$;


CREATE OR REPLACE FUNCTION public.is_coordinator()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.coordinator
        WHERE user_id = auth.uid()
    );
$$;


CREATE OR REPLACE FUNCTION public.is_organizer()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.organizer
        WHERE user_id = auth.uid()
    );
$$;


CREATE OR REPLACE FUNCTION public.is_assigned_organizer(p_event_id BIGINT)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.organizer_assignments
        WHERE event_id = p_event_id
          AND organizer_id = auth.uid()
    );
$$;


-- ============================================================
-- BOOKING CAPACITY / WAITLIST
-- ============================================================

CREATE OR REPLACE FUNCTION public.set_booking_status()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SET search_path = ''
AS $$
DECLARE
    event_capacity INTEGER;
    confirmed_count INTEGER;
BEGIN

    -- Lock bookings for this event so simultaneous reservations
    -- cannot exceed capacity.
    PERFORM pg_advisory_xact_lock(NEW.event_id);

    SELECT capacity
    INTO event_capacity
    FROM public.events
    WHERE event_id = NEW.event_id;

    IF event_capacity IS NULL THEN
        RAISE EXCEPTION 'Event does not exist.';
    END IF;

    SELECT COUNT(*)
    INTO confirmed_count
    FROM public.bookings
    WHERE event_id = NEW.event_id
      AND status = 'Confirmed';

    IF confirmed_count >= event_capacity THEN
        NEW.status := 'Waitlisted';
    ELSE
        NEW.status := 'Confirmed';
    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER automatic_booking_status_trigger
BEFORE INSERT ON public.bookings
FOR EACH ROW
EXECUTE FUNCTION public.set_booking_status();


-- ============================================================
-- EVENT VALIDATION
-- ============================================================

CREATE OR REPLACE FUNCTION public.validate_event_capacity()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SET search_path = ''
AS $$
DECLARE
    max_capacity INTEGER;
BEGIN

    SELECT room_capacity
    INTO max_capacity
    FROM public.venues
    WHERE venue_id = NEW.venue_id;

    IF max_capacity IS NULL THEN
        RAISE EXCEPTION 'Venue does not exist.';
    END IF;

    IF NEW.capacity > max_capacity THEN
        RAISE EXCEPTION
            'Event capacity cannot exceed venue room capacity.';
    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER validate_event_capacity_trigger
BEFORE INSERT OR UPDATE ON public.events
FOR EACH ROW
EXECUTE FUNCTION public.validate_event_capacity();


CREATE OR REPLACE FUNCTION public.prevent_event_overlap()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SET search_path = ''
AS $$
BEGIN

    IF EXISTS (
        SELECT 1
        FROM public.events e
        WHERE e.venue_id = NEW.venue_id
          AND e.event_date = NEW.event_date
          AND e.event_id <> COALESCE(NEW.event_id, 0)
          AND NEW.start_time < e.end_time
          AND NEW.end_time > e.start_time
    )
    THEN
        RAISE EXCEPTION
            'Another event is already scheduled in this venue during this time.';
    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER prevent_event_overlap_trigger
BEFORE INSERT OR UPDATE ON public.events
FOR EACH ROW
EXECUTE FUNCTION public.prevent_event_overlap();


-- ============================================================
-- ATTENDANCE VALIDATION
-- ============================================================

CREATE OR REPLACE FUNCTION public.validate_attendance()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SET search_path = ''
AS $$
DECLARE
    booking_event BIGINT;
    current_booking_status VARCHAR(20);
BEGIN

    SELECT event_id, status
    INTO booking_event, current_booking_status
    FROM public.bookings
    WHERE booking_id = NEW.booking_id;

    IF booking_event IS NULL THEN
        RAISE EXCEPTION 'Booking does not exist.';
    END IF;

    IF current_booking_status <> 'Confirmed' THEN
        RAISE EXCEPTION
            'Attendance can only be recorded for confirmed bookings.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM public.organizer_assignments
        WHERE event_id = booking_event
          AND organizer_id = NEW.organizer_id
    )
    THEN
        RAISE EXCEPTION
            'Organizer is not assigned to this event.';
    END IF;

    RETURN NEW;
END;
$$;


CREATE TRIGGER validate_attendance_trigger
BEFORE INSERT OR UPDATE ON public.attendance_logs
FOR EACH ROW
EXECUTE FUNCTION public.validate_attendance();


-- ============================================================
-- ROW LEVEL SECURITY
-- RLS is enabled on EVERY application table.
-- ============================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendee ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coordinator ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizer ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizer_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;


-- ============================================================
-- USERS POLICIES
-- Readers: user themselves, coordinators, organizers.
-- Writers: user may update their own profile.
-- ============================================================

CREATE POLICY "Users read own profile"
ON public.users
FOR SELECT TO authenticated
USING (user_id = auth.uid());


CREATE POLICY "Coordinators read users"
ON public.users
FOR SELECT TO authenticated
USING (public.is_coordinator());


CREATE POLICY "Organizers read users"
ON public.users
FOR SELECT TO authenticated
USING (public.is_organizer());


CREATE POLICY "Users update own profile"
ON public.users
FOR UPDATE TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());


-- ============================================================
-- ATTENDEE POLICIES
-- Readers: attendee themselves, coordinators, organizers.
-- Writers: attendee may update their own attendee record.
-- ============================================================

CREATE POLICY "Attendees read own record"
ON public.attendee
FOR SELECT TO authenticated
USING (user_id = auth.uid());


CREATE POLICY "Coordinators read attendees"
ON public.attendee
FOR SELECT TO authenticated
USING (public.is_coordinator());


CREATE POLICY "Organizers read attendees"
ON public.attendee
FOR SELECT TO authenticated
USING (public.is_organizer());


CREATE POLICY "Attendees update own record"
ON public.attendee
FOR UPDATE TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());


-- ============================================================
-- COORDINATOR POLICIES
-- Readers: coordinator themselves / other coordinators.
-- Writers: coordinators manage coordinator records.
-- ============================================================

CREATE POLICY "Coordinators read own record"
ON public.coordinator
FOR SELECT TO authenticated
USING (
    user_id = auth.uid()
    OR public.is_coordinator()
);


CREATE POLICY "Coordinators create coordinator records"
ON public.coordinator
FOR INSERT TO authenticated
WITH CHECK (public.is_coordinator());


CREATE POLICY "Coordinators update coordinator records"
ON public.coordinator
FOR UPDATE TO authenticated
USING (public.is_coordinator())
WITH CHECK (public.is_coordinator());


-- ============================================================
-- ORGANIZER POLICIES
-- Readers: organizer themselves and coordinators.
-- Writers: coordinators manage organizer records.
-- ============================================================

CREATE POLICY "Organizers read own record"
ON public.organizer
FOR SELECT TO authenticated
USING (
    user_id = auth.uid()
    OR public.is_coordinator()
);


CREATE POLICY "Coordinators create organizers"
ON public.organizer
FOR INSERT TO authenticated
WITH CHECK (public.is_coordinator());


CREATE POLICY "Coordinators update organizers"
ON public.organizer
FOR UPDATE TO authenticated
USING (public.is_coordinator())
WITH CHECK (public.is_coordinator());


-- ============================================================
-- VENUE POLICIES
-- Readers: authenticated users.
-- Writers: coordinators.
-- ============================================================

CREATE POLICY "Authenticated users read venues"
ON public.venues
FOR SELECT TO authenticated
USING (true);


CREATE POLICY "Coordinators create venues"
ON public.venues
FOR INSERT TO authenticated
WITH CHECK (public.is_coordinator());


CREATE POLICY "Coordinators update venues"
ON public.venues
FOR UPDATE TO authenticated
USING (public.is_coordinator())
WITH CHECK (public.is_coordinator());


CREATE POLICY "Coordinators delete venues"
ON public.venues
FOR DELETE TO authenticated
USING (public.is_coordinator());


-- ============================================================
-- EVENT POLICIES
-- Readers: authenticated users.
-- Writers: coordinator who owns the event.
-- ============================================================

CREATE POLICY "Authenticated users read events"
ON public.events
FOR SELECT TO authenticated
USING (true);


CREATE POLICY "Coordinators create own events"
ON public.events
FOR INSERT TO authenticated
WITH CHECK (
    public.is_coordinator()
    AND coordinator_id = auth.uid()
);


CREATE POLICY "Coordinators update own events"
ON public.events
FOR UPDATE TO authenticated
USING (
    coordinator_id = auth.uid()
    AND public.is_coordinator()
)
WITH CHECK (
    coordinator_id = auth.uid()
    AND public.is_coordinator()
);


CREATE POLICY "Coordinators delete own events"
ON public.events
FOR DELETE TO authenticated
USING (
    coordinator_id = auth.uid()
    AND public.is_coordinator()
);


-- ============================================================
-- BOOKING POLICIES
-- Readers: attendee owner, event coordinator,
--          assigned organizer.
-- Writers: attendee creates/updates their own booking.
-- ============================================================

CREATE POLICY "Attendees read own bookings"
ON public.bookings
FOR SELECT TO authenticated
USING (user_id = auth.uid());


CREATE POLICY "Attendees create own bookings"
ON public.bookings
FOR INSERT TO authenticated
WITH CHECK (
    user_id = auth.uid()
    AND public.is_attendee()
);


CREATE POLICY "Attendees update own bookings"
ON public.bookings
FOR UPDATE TO authenticated
USING (
    user_id = auth.uid()
    AND public.is_attendee()
)
WITH CHECK (user_id = auth.uid());


CREATE POLICY "Coordinators read bookings for own events"
ON public.bookings
FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.events e
        WHERE e.event_id = bookings.event_id
          AND e.coordinator_id = auth.uid()
    )
);


CREATE POLICY "Assigned organizers read event bookings"
ON public.bookings
FOR SELECT TO authenticated
USING (
    public.is_assigned_organizer(event_id)
);


-- ============================================================
-- ORGANIZER ASSIGNMENT POLICIES
-- Readers: assigned organizer and event coordinator.
-- Writers: coordinator who owns the event.
-- ============================================================

CREATE POLICY "Organizers read own assignments"
ON public.organizer_assignments
FOR SELECT TO authenticated
USING (organizer_id = auth.uid());


CREATE POLICY "Coordinators read own event assignments"
ON public.organizer_assignments
FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.events e
        WHERE e.event_id = organizer_assignments.event_id
          AND e.coordinator_id = auth.uid()
    )
);


CREATE POLICY "Coordinators assign organizers"
ON public.organizer_assignments
FOR INSERT TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.events e
        WHERE e.event_id = organizer_assignments.event_id
          AND e.coordinator_id = auth.uid()
    )
);


CREATE POLICY "Coordinators remove organizer assignments"
ON public.organizer_assignments
FOR DELETE TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.events e
        WHERE e.event_id = organizer_assignments.event_id
          AND e.coordinator_id = auth.uid()
    )
);


-- ============================================================
-- ATTENDANCE POLICIES
-- Readers: attendee owner, assigned organizer,
--          event coordinator.
-- Writers: assigned organizer for a confirmed booking.
-- ============================================================

CREATE POLICY "Attendees read own attendance"
ON public.attendance_logs
FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.bookings b
        WHERE b.booking_id = attendance_logs.booking_id
          AND b.user_id = auth.uid()
    )
);


CREATE POLICY "Assigned organizers read attendance"
ON public.attendance_logs
FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.bookings b
        WHERE b.booking_id = attendance_logs.booking_id
          AND public.is_assigned_organizer(b.event_id)
    )
);


CREATE POLICY "Coordinators read attendance for own events"
ON public.attendance_logs
FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.bookings b
        JOIN public.events e
          ON e.event_id = b.event_id
        WHERE b.booking_id = attendance_logs.booking_id
          AND e.coordinator_id = auth.uid()
    )
);


CREATE POLICY "Assigned organizers create attendance"
ON public.attendance_logs
FOR INSERT TO authenticated
WITH CHECK (
    organizer_id = auth.uid()
    AND EXISTS (
        SELECT 1
        FROM public.bookings b
        WHERE b.booking_id = attendance_logs.booking_id
          AND b.status = 'Confirmed'
          AND public.is_assigned_organizer(b.event_id)
    )
);


CREATE POLICY "Assigned organizers update attendance"
ON public.attendance_logs
FOR UPDATE TO authenticated
USING (
    organizer_id = auth.uid()
    AND EXISTS (
        SELECT 1
        FROM public.bookings b
        WHERE b.booking_id = attendance_logs.booking_id
          AND b.status = 'Confirmed'
          AND public.is_assigned_organizer(b.event_id)
    )
)
WITH CHECK (
    organizer_id = auth.uid()
    AND EXISTS (
        SELECT 1
        FROM public.bookings b
        WHERE b.booking_id = attendance_logs.booking_id
          AND b.status = 'Confirmed'
          AND public.is_assigned_organizer(b.event_id)
    )
);